language: node_js

node_js:
  - 0.12
  - 5.0
  - stable

before_script:
  - "npm install -g grunt-cli"
  - "npm install"

script:
  - "npm run build"
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com
